Add bgen support
lifebit-ai/gwas pull request #122
Opened 2021-11-16 11:42 UTC by evagradovich

2021-11-22 12:54 UTC, Vlad-Dembrovskyi requested changes

2021-11-22 12:54 UTC, Vlad-Dembrovskyi commented on .github/workflows/ci.yml
> +  test_binary_bgen:
what is the difference between `test_binary_bgen` and previous `test_binary_input_folder_location` if they both use exact same command and config file: `--config conf/test_binary_with_input_folder.config` ?

2021-11-22 12:54 UTC, Vlad-Dembrovskyi commented on README.md
> +  --pheno_data "s3://lifebit-featured-datasets/projects/gel/cb_binary_pheno.phe" \
```Suggestion
  --pheno_data "s3://lifebit-featured-datasets/projects/gel/gel-gwas/cb_binary_pheno.phe" \
```
Checked the file existence and its not there. Found it under `gel-gwas` folder in same place. Is that the one?

2021-11-22 12:54 UTC, Vlad-Dembrovskyi commented on README.md
> +  --pheno_data "s3://lifebit-featured-datasets/projects/gel/cb_binary_pheno.phe" \
![image](https://user-images.githubusercontent.com/64809705/142861740-2eab8d37-b55a-492b-a94f-bbf05a4545e1.png)

2021-11-22 12:54 UTC, Vlad-Dembrovskyi commented on .github/workflows/ci.yml
>            nextflow run ${GITHUB_WORKSPACE} --config conf/test_binary_with_input_folder.config
```Suggestion
          nextflow run ${GITHUB_WORKSPACE} --config conf/test_binary_bgen.config
```
I believe that's the right config for this test profile?

2021-11-22 12:54 UTC, Vlad-Dembrovskyi commented on docs/usage_and_parameters.md
> +- **--genotype_files_list** : path/url to CSV file containing chr, path to file and corresponding index, e.g. for VCF - chr,vcf,index(.csi) and for .bgen files - chr,bgen,index(.bgi).
```Suggestion
- **--genotype_files_list** : path/url to CSV file containing chr, path to file and corresponding index, e.g. for VCF - chr,vcf,index(.csi) and for .bgen files - chr,bgen,index(.bgi). NOTE: chr must be in numeric format. Not `chr1`,`chr2`,`chr3`, but `1`,`2`,`3`.
```
I had an issue recently where I've set chromosomes as chr1, chr2, chr3, and pipeline failed for me at the last `report` step. I don't know if its still an issue on this branch. If its not an issue anymore, feel free to ignore the suggestion. If it is - lets add the suggestion (for now at least), and if that's a solvable issue (not software-dependent) lets solve it.

Example error I got:
![image](https://user-images.githubusercontent.com/64809705/142862824-5f11bc5f-1abc-430e-b660-6793da4049a0.png)

2021-11-22 12:54 UTC, Vlad-Dembrovskyi commented on main.nf
> +  output:
I'd add tabs from here too, to keep the visual hierarchy.

2021-11-22 12:54 UTC, Vlad-Dembrovskyi commented on main.nf
> +     --memory ${params.plink_memory} \
Why don't we set the memory from `${task.memory}`? Or are these two not the same for our plink case?

2021-11-22 12:54 UTC, Vlad-Dembrovskyi commented on nextflow.config
>  process {
Can we move this below to another instance of `pcocess {}` scope so we only have all process-related items in one place? 

Also, can we please move the single resulting `process {}` scope here beneath the `profiles {}` scope? This way profiles will be able to overwrite some parameters/values used for setting process-specific configs. If the `process {}` scope will be above `profiles {}` scope then profiles won't be able to overwrite any process configs, unless profiles themselves define a `process {}` scope, which is not the best practice. It would be best to keep profiles only for `params {}` and optionally executor-specific things, and only define `process {}` in main `nextflow.config`. 

If there is some considerable counter-argument to above for this specific workflow, we can sure keep it as it is now, its not something wrong on itself.

2021-11-22 12:54 UTC, Vlad-Dembrovskyi commented on nextflow.config
> +  plink_memory = 155000
Isn't it too dangerous to set such a high default? I understand that probably GWAS pipelines will usually need a lot, but that would meant that all new jobs that users will start to try out the pipeline will fail because I don't think they will select a big enough machine. That would make this parameter required instead of optional. 

Could we pick a more feasible default value for this, like 16 Gb maybe? And warn on main readme page that by default pipeline requires 16Gb unless you change that with `--plink_memory` parameter.

2021-11-22 14:05 UTC, evagradovich commented on .github/workflows/ci.yml
> +  test_binary_bgen:
Thanks for spotting, this was a copy paste error - it should point to a different config. Fixed

2021-11-22 14:19 UTC, evagradovich commented on README.md
> +  --pheno_data "s3://lifebit-featured-datasets/projects/gel/cb_binary_pheno.phe" \
Yes, thank you for spotting - fixed

2021-11-22 14:25 UTC, evagradovich commented on docs/usage_and_parameters.md
> +- **--genotype_files_list** : path/url to CSV file containing chr, path to file and corresponding index, e.g. for VCF - chr,vcf,index(.csi) and for .bgen files - chr,bgen,index(.bgi).
Thank you for raising @Vlad-Dembrovskyi . There is an open issue for fixing this behaviour (https://github.com/lifebit-ai/gwas/issues/36) and it also affects using X chromosome as input so this will be tackled in the fix for X chromosome in a future PR

2021-11-22 15:21 UTC, evagradovich commented on nextflow.config
>  process {
Implemented - thank you for suggestion!

2021-11-22 15:24 UTC, evagradovich commented on nextflow.config
> +  plink_memory = 155000
Default changed to 16Gb, and a note added to README

2021-11-22 15:25 UTC, evagradovich commented on main.nf
> +     --memory ${params.plink_memory} \
plink assigns half of RAM available for its function calls, `plink_memory` allows to override this behaviour

2021-11-23 08:56 UTC, evagradovich commented
<img width="1363" alt="Screenshot 2021-11-23 at 08 40 27" src="https://user-images.githubusercontent.com/33654687/142994893-b79e05a5-5e00-449b-927a-42bc62e66db5.png">
<img width="1267" alt="Screenshot 2021-11-23 at 08 40 39" src="https://user-images.githubusercontent.com/33654687/142994899-af1beb8d-0cad-4d62-91aa-ea003fab8887.png">
<img width="1350" alt="Screenshot 2021-11-23 at 08 53 47" src="https://user-images.githubusercontent.com/33654687/142994900-58d9be09-c175-4bdb-afb6-344427a13435.png">
Small test with .bgen files finishes successfully in Lifebit Internal Production but fails with bigger dataset with memory allocation errors. Subsequent PR will involve memory optimization in light of GWAS benchmarks performed and will address issue https://github.com/lifebit-ai/gwas/issues/126.

2021-11-24 09:03 UTC, Vlad-Dembrovskyi approved these changes
Run the tests and example command locally, looks good to me!
![image](https://user-images.githubusercontent.com/64809705/143207165-d3fd2d46-6b10-4396-9cea-5cd58084566d.png)

2021-11-24 09:06 UTC, merged